### ISSUE TITLE
Unable to create docs from scaffolded template from yo verb

### ISSUE THREAD

**Issue by pavelbinar** [verbose/verb-cli#2]
I generated new verb project via `yo verb` and than run command `verb`

Log: https://gist.github.com/pavelbinar/44d92accb8cbfd0cc77e#file-gistfile1-txt-L42

**Comment by doowb** [comment]
I've seen this error too.It's just a missing dependency. I'll do a fix in a little bit.

**Comment by doowb** [comment]
Actually, I'm not sure where to update this. @jonschlinkert probably has a better idea.

As a work around, you just have to do `npm install verb-tag-jscomments --save-dev`

**Comment by jonschlinkert** [comment]
I'll take a look this evening, thanks for reporting it!

**Comment by jonschlinkert** [comment]
I've been making a bunch of related fixes, I didn't forget about this, just wanted to let you know!

**Comment by pavelbinar** [comment]
Hi all!
@doowb Yes, `npm install verb-tag-jscomments --save-dev` worked. Thanks.
@jonschlinkert No problem, Thanks for info.

**Comment by jonschlinkert** [comment]
:+1:

**Comment by jonschlinkert** [comment]
closing due to age, since verb and verb-cli have been refactored since
