### ISSUE TITLE
0.5.0 tracking

### ISSUE THREAD

**Issue by jonschlinkert** [verbose/verb-cli#3]
@stefanwalther, I deleted the repo that was here, then moved `assemble/verb-cli` here. There were only a couple of issues here before, but my apologies I forgot to copy them down before moving the repo. Feel free to add new issues here or list the issues you're having on this one so I can get them fixed. Thanks!

**Comment by stefanwalther** [comment]
Hi @jonschlinkert, OK, all fine, I'll give it a new try with this repo and tell you what the status is ...

**Comment by jonschlinkert** [comment]
closing. 0.6.0 of verb-cli was released, and 0.7.0 of verb was released with 200+ commits
