### ISSUE TITLE
TypeError verb `... init/load.js`

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb-cli#5]
`verb@0.8.6` and `verb-cli@0.7.2`

and again problems... I dont have even one time that I tried to run verb and to work.

``` js
/home/charlike/.nvm/versions/io.js/v2.3.4/lib/node_modules/verb-cli/node_modules/verb/lib/transforms/init/load.js:29
  if (paths.hasOwnProperty(name)) {
           ^
TypeError: Cannot read property 'hasOwnProperty' of undefined
```

**Comment by jonschlinkert** [comment]
ok, I understand it's frustrating. but let's just stick to the issue so I can try to fix it. 

sorry these bugs are still happening.. I'm refactoring the entire ecosystem of underlying libs that make verb work - e.g. I haven't had time to monkey-patch these issues in verb b/c I'm trying to fix "the root" issues. @doowb and I are getting very close to releasing some awesome things :)

**Comment by doowb** [comment]
Try getting latest of `verb-cli` and `verb` globally now:

``` sh
$ npm cache clear -g && npm i verb-cli verb -g
```

**Comment by tunnckoCore** [comment]
Why is `verb` needed globally when we have `verb-cli` ?

Yes it seems that simple verb.md with name and description works now.

**Comment by doowb** [comment]
> Why is verb needed globally when we have verb-cli ?

`verb` is not needed globally, but then it would be needed in the local node_modules.
This allows making updates to `verb` independently of `verb-cli`.

For convenience, install `verb` globally so you don't have to have it as a devDependency in your local projects just to build a readme.
